name: Linux build
on:
    push:
        branches: [master]
jobs:
    linux-build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: i686-unknown-linux-gnu
                  override: true

            - name: Install g++-multilib
              run: |
                  sudo apt update
                  sudo apt install g++-multilib -y
            - name: Build auxmos
              run: cargo build --target=i686-unknown-linux-gnu --release --features citadel_reactions
